=== jetty/jetty.project/jetty-core/jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
This is the document type descriptor for the
org.eclipse.jetty.xml.XmlConfiguration class.  It allows a java object to be
configured by with a sequence of Set, Put and Call elements.  These tags are
mapped to methods on the object to be configured as follows:

  <Set  name="Test">value</Set>              ==  obj.setTest("value");
  <Put  name="Test">value</Put>              ==  obj.put("Test","value");
  <Call name="test"><Arg>value</Arg></Call>  ==  obj.test("value");

Values themselves may be configured objects that are created with the
<New> tag or returned from a <Call> tag.

Values are matched to arguments on a best effort approach, but types
my be specified if a match is not achieved.
-->

<!ENTITY % CONFIG "Set|Get|Put|Call|New|Ref|Array|Map|Property">
<!ENTITY % VALUE "#PCDATA|Get|Call|New|Ref|Array|Map|SystemProperty|Env|Property">
<!ENTITY % TYPE_ATTR "type CDATA #IMPLIED " >
<!ENTITY % CLASS_ATTR "class CDATA #IMPLIED" >
<!ENTITY % NAME_ATTR_REQUIRED "name CDATA #REQUIRED" >
<!ENTITY % NAME_ATTR "name CDATA #IMPLIED" >
<!ENTITY % PROPERTY_ATTR "property CDATA #IMPLIED" >
<!ENTITY % DEPRECATED_ATTR "deprecated CDATA #IMPLIED" >
<!ENTITY % DEFAULT_ATTR "default CDATA #IMPLIED" >
<!ENTITY % ID_ATTR "id ID #IMPLIED" >
<!ENTITY % ARG_ATTR "arg CDATA #IMPLIED" >
<!ENTITY % ITEM_ATTR "item CDATA #IMPLIED" >
<!ENTITY % REF_ATTR "refid CDATA #IMPLIED" >
<!ENTITY % ID_ATTR_REQUIRED "id ID #REQUIRED" >

<!--
Configure Element.
This is the root element that specifies the class of object that
can be configured:

    <Configure class="com.acme.MyClass"> ... </Configure>
-->
<!ELEMENT Configure (Id?,Class?,Arg*,(%CONFIG;)*) >
<!ATTLIST Configure %ID_ATTR; %CLASS_ATTR; >


<!--
Set Element.
This element maps to a call to a setter method or field on the current object.
The name and optional type attributes are used to select the setter
method. If the name given is xxx, then a setXxx method is used, or
the xxx field is used of setXxx cannot be found.

A Set element can contain value text and/or the value objects returned
by other elements such as Call, New, SystemProperty, etc.
If no value type is specified, then white
space is trimmed out of the value. If it contains multiple value
elements they are added as strings before being converted to any
specified type.

If the property attribute is set to a property name, then the set is
performed only if the property has a non null value. If the Set element
contains no value then the the property attribute value is used as the set
value.

A Set with a class attribute is treated as a static set method invocation.
-->
<!ELEMENT Set (%VALUE;)* >
<!ATTLIST Set %ID_ATTR; %CLASS_ATTR; %NAME_ATTR_REQUIRED; %TYPE_ATTR; %PROPERTY_ATTR;>


<!--
Get Element.
This element maps to a call to a getter method or field on the current object.
The name attribute is used to select the get method.
If the name given is xxx, then a getXxx method is used, or
the xxx field is used if getXxx cannot be found.
A Get element can contain other elements such as Set, Put, Call, etc.
which act on the object returned by the get call.

A Get with a class attribute is treated as a static get method or field.
-->
<!ELEMENT Get (Id?,Name?,Class?,(%CONFIG;)*) >
<!ATTLIST Get %ID_ATTR; %NAME_ATTR; %CLASS_ATTR; >


<!--
Put Element.
This element maps to a call to a put method on the current object,
which must implement the Map interface. The name attribute is used
as the put key and the optional type attribute can force the type
of the value.

A Put element can contain value text and/or value elements such as Call,
New, SystemProperty, etc. If no value type is specified, then white
space is trimmed out of the value. If it contains multiple value
elements they are added as strings before being converted to any
specified type.
-->
<!ELEMENT Put (%VALUE;)* >
<!ATTLIST Put %NAME_ATTR_REQUIRED; %TYPE_ATTR; >


<!--
Id Element.
This element is the equivalent of the id attribute.
-->
<!ELEMENT Id (%VALUE;)* >


<!--
Name element.
This element is the equivalent of the name attribute.
-->
<!ELEMENT Name (%VALUE;)* >


<!--
Deprecated element.
This element is the equivalent of the deprecated attribute.
-->
<!ELEMENT Deprecated (%VALUE;)* >


<!--
Default element.
This element is the equivalent of the default attribute.
-->
<!ELEMENT Default (%VALUE;)* >


<!--
Class element.
This element is the equivalent of the class attribute.
-->
<!ELEMENT Class (%VALUE;)* >


<!--
Type element.
This element is the equivalent of the type attribute.
-->
<!ELEMENT Type (%VALUE;)* >


<!--
Call Element.
This element maps to an arbitrary call to a method on the current object,
The name attribute and Arg elements are used to select the method.

A Call element can contain a sequence of Arg elements followed by
a sequence of other elements such as Set, Put, Call, etc. which act on any object
returned by the original call:

 <Call id="o2" name="test">
   <Arg>value1</Arg>
   <Set name="Test">Value2</Set>
 </Call>

This is equivalent to:

 Object o2 = o1.test("value1");
 o2.setTest("value2");

A Call with a class attribute is treated as a static call.
-->
<!ELEMENT Call (Id?,Name?,Class?,Arg*,(%CONFIG;)*) >
<!ATTLIST Call %ID_ATTR; %NAME_ATTR; %CLASS_ATTR; %ARG_ATTR; >


<!--
Arg Element.
This element defines a positional or optional named argument for the
Call and New elements. The optional type attribute can force the type
of the value.

An Arg element can contain value text and/or value elements such as Call,
New, SystemProperty, etc. If no value type is specified, then white
space is trimmed out of the value. If it contains multiple value
elements they are added as strings before being converted to any
specified type.
-->
<!ELEMENT Arg (%VALUE;)* >
<!ATTLIST Arg %NAME_ATTR; %TYPE_ATTR; >


<!--
New Element.
This element allows the creation of a new object as part of a
value for elements such as Set, Put, Arg, etc. The class attribute
determines the type of the new object and the contained Arg elements
are used to select the constructor for the new object.

A New element can contain a sequence of Arg elements followed by
a sequence of elements such as Set, Put, Call, etc. elements
which act on the new object:

 <New id="o" class="com.acme.MyClass">
   <Arg>value1</Arg>
   <Set name="test">Value2</Set>
 </New>

This is equivalent to:

 Object o = new com.acme.MyClass("value1");
 o.setTest("Value2");
-->
<!ELEMENT New (Id?,Class?,Arg*,(%CONFIG;)*) >
<!ATTLIST New %ID_ATTR; %CLASS_ATTR; %ARG_ATTR; >


<!--
Ref Element.
This element allows a previously created object to be referenced by id.  The
attribute refid is used to specify the id of another object (the attribute id can
also be used, but it's use is deprecated).
A Ref element can contain a sequence of elements such as Set, Put, Call, etc.
which act on the referenced object.

 <Ref refid="myobject">
   <Set name="Test">Value2</Set>
 </New>
-->
<!ELEMENT Ref (Id?,(%CONFIG;)*) >
<!ATTLIST Ref %ID_ATTR; %REF_ATTR;>


<!--
Array Element.
This element allows the creation of a new array as part of a
value of elements such as Set, Put, Arg, etc. The type attribute determines
the type of the new array and the contained Item elements
are used for each element of the array:

 <Array type="java.lang.String">
   <Item>value0</Item>
   <Item><New class="java.lang.String"><Arg>value1</Arg></New></Item>
 </Array>

This is equivalent to:
 String[] a = new String[] { "value0", new String("value1") };
-->
<!ELEMENT Array (Id?,Type?,Item*) >
<!ATTLIST Array %ID_ATTR; %TYPE_ATTR; %ITEM_ATTR; >


<!--
Map Element.
This element allows the creation of a new map as part of a
value of elements such as Set, Put, Arg, etc. The type attribute determines
the type of the new array and the contained Item elements
are used for each element of the array:

 <Map>
   <Entry>
     <Item>keyName</Item>
     <Item><New class="java.lang.String"><Arg>value1</Arg></New></Item>
   </Entry>
 </Map>

This is equivalent to:
 Map m = new HashMap();
 m.put("keyName", new String("value1"));
-->
<!ELEMENT Map (Id?,Class?,Entry*) >
<!ATTLIST Map %ID_ATTR; %CLASS_ATTR; >
<!ELEMENT Entry (Item,Item) >


<!--
Item Element.
This element defines an entry for the Array or Map Entry elements.
The optional type attribute can force the type of the value.

An Item element can contain value text and/or the value object of
elements such as Call, New, SystemProperty, etc. If no value type
is specified, then white space is trimmed out of the value.
If it contains multiple value elements they are added as strings
before being converted to any specified type.
-->
<!ELEMENT Item (%VALUE;)* >
<!ATTLIST Item %ID_ATTR; %TYPE_ATTR; >


<!--
System Property Element.
This element allows JVM System properties to be retrieved as
part of the value of elements such as Set, Put, Arg, etc.
The name attribute specifies the property name and the optional
default attribute provides a default value.

 <SystemProperty name="Test" default="value" />

This is equivalent to:

 System.getProperty("Test","value");
-->
<!ELEMENT SystemProperty (Id?,Name?,Deprecated*,Default?) >
<!ATTLIST SystemProperty %ID_ATTR; %NAME_ATTR; %DEPRECATED_ATTR; %DEFAULT_ATTR; >


<!--
Environment variable Element.
This element allows OS Environment variables to be retrieved as
part of the value of elements such as Set, Put, Arg, etc.
The name attribute specifies the env variable name and the optional
default attribute provides a default value.

 <Env name="Test" default="value" />

This is equivalent to:

 String v=System.getEnv("Test");
 if (v==null) v="value";
-->
<!ELEMENT Env (Id?,Name?,Deprecated*,Default?) >
<!ATTLIST Env %ID_ATTR; %NAME_ATTR; %DEPRECATED_ATTR; %DEFAULT_ATTR; >


<!--
Property Element.
This element allows arbitrary properties to be retrieved by name.
The name attribute specifies the property name and the optional
default attribute provides a default value.
-->
<!ELEMENT Property (Id?,Name?,Deprecated*,Default?) >
<!ATTLIST Property %ID_ATTR; %NAME_ATTR; %DEPRECATED_ATTR; %DEFAULT_ATTR; >

=== jetty/jetty.project/jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-client/src/test/resources/jetty-websocket-httpclient.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_10_0.dtd">

<Configure class="org.eclipse.jetty.client.HttpClient">
  <Arg>
    <New class="org.eclipse.jetty.client.transport.HttpClientTransportOverHTTP">
      <Arg>
        <New class="org.eclipse.jetty.io.ClientConnector">
          <Call name="setSslContextFactory">
            <Arg>
              <New class="org.eclipse.jetty.util.ssl.SslContextFactory$Client">
                <!-- websocket.org uses WEAK cipher suites -->
                <Set name="excludeCipherSuites">
                  <Array type="java.lang.String"></Array>
                </Set>
              </New>
            </Arg>
          </Call>
        </New>
      </Arg>
    </New>
  </Arg>
</Configure>

=== jetty/jetty.project/jetty-infinispan/infinispan-remote/src/main/config-template/etc/sessions/infinispan/infinispan-remote.xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">

<Configure id="Server" class="org.eclipse.jetty.server.Server">

  <!-- ===================================================================== -->
  <!-- Read hotrod-client.properties file                                    -->
  <!-- ===================================================================== -->
  <New id="properties" class="java.util.Properties">
    <Call name="load">
      <Arg>
          <New class="java.io.FileInputStream">
              <Arg><Property name="jetty.base"/>/resources/hotrod-client.properties</Arg>
          </New>
      </Arg>
    </Call>
  </New>

  <!-- ===================================================================== -->
  <!-- Convert properties to configuration                                   -->
  <!-- ===================================================================== -->
  <New class="org.infinispan.client.hotrod.configuration.ConfigurationBuilder">
    <Call name="withProperties">
      <Arg><Ref refid="properties"/></Arg>
    </Call>
    <Call name="marshaller">
      <Arg>
          <New class="org.infinispan.client.hotrod.marshall.ProtoStreamMarshaller"/>
       </Arg>
    </Call>
    <Call id="config" name="build"/>
  </New>

  <!-- ===================================================================== -->
  <!-- Get a reference to the remote cachemanager.                           -->
  <!-- ===================================================================== -->
  <New id="hotrodMgr" class="org.infinispan.client.hotrod.RemoteCacheManager">
    <Arg><Ref refid="config"/></Arg>
  </New>


  <!-- ===================================================================== -->
  <!-- Set up custom session serialization.                                  -->
  <!-- ===================================================================== -->
  <Call id="serial_context" class="org.infinispan.client.hotrod.marshall.ProtoStreamMarshaller" name="getSerializationContext">
    <Arg>
      <Ref refid="hotrodMgr"/>
    </Arg>
    <Call name="registerProtoFiles">
      <Arg>
        <New class="org.infinispan.protostream.FileDescriptorSource">
          <Call name="addProtoFiles">
            <Arg>
              <Array type="java.lang.String">
                <Item>/session.proto</Item>
              </Array>
            </Arg>
          </Call>
        </New>
      </Arg>
    </Call>
    <Call name="registerMarshaller">
      <Arg>
        <New class="org.eclipse.jetty.session.infinispan.SessionDataMarshaller"/>
      </Arg>
    </Call>
  </Call>


  <!-- ===================================================================== -->
  <!-- Get a reference to the remote cache.                                  -->
  <!-- ===================================================================== -->
  <Ref refid="hotrodMgr">
    <Call id="cache" name="getCache">
      <Arg><Property name="jetty.session.infinispan.remoteCacheName" default="sessions"/></Arg>
    </Call>
  </Ref>
  
  <!-- ===================================================================== -->
  <!-- Set queryMgrFactory reference to NullQueryManagerFactory              -->
  <!-- ===================================================================== -->
  <New id="queryMgrFactory" class="org.eclipse.jetty.session.infinispan.NullQueryManagerFactory"/>
  
</Configure>

=== jetty/jetty.project/jetty-ee12/jetty-ee12-jaspi/jetty-ee12-jaspi/src/main/config/etc/jaspi/jetty-ee12-jaspi-demo.xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure>
  <Call class="jakarta.security.auth.message.config.AuthConfigFactory" name="getFactory">
    <Call name="registerConfigProvider">

      <!-- The Jetty provided implementation of AuthConfigProvider which will wrap a ServerAuthModule. -->
      <Arg type="String">org.eclipse.jetty.ee.security.jaspi.provider.JaspiAuthConfigProvider</Arg>

      <!-- A Map of initialization properties. -->
      <Arg>
        <Map>
          <Entry>
            <!-- Provide the fully qualified classname of the ServerAuthModule to be used. -->
            <Item>ServerAuthModule</Item>
            <Item>org.eclipse.jetty.ee.security.jaspi.modules.BasicAuthenticationAuthModule</Item>
          </Entry>
          <Entry>
            <!-- Realm as utilised by Jetty Security  -->
            <Item>org.eclipse.jetty.ee.security.jaspi.modules.RealmName</Item>
            <Item>Test Realm</Item>
          </Entry>
        </Map>
      </Arg>

      <!-- Message Layer Identifier as per spec chapter 3.1  -->
      <Arg type="String">HttpServlet</Arg>

      <!-- Application Context Identifier as per spec chapter 3.2

        AppContextID ::= hostname blank context-path
        The algorithm applied here will use the
        _serverName on the configured JaspiAuthenticatorFactory (if set) and try to match it
        against the "server" part (in the "server /test" example below).
        Next it will try to match the ServletContext#getVirtualServerName to the "server" part.
        If neither are set, it will then try to match the first Subject's principal name, and finally fall back to
        the default value "server" if none are available.

        The context-path should match the context path where this applies.
      -->
      <Arg type="String">server /test</Arg>

      <!-- A friendly description of the provided auth-module. -->
      <Arg type="String">A simple provider using HTTP BASIC authentication.</Arg>
    </Call>
  </Call>
</Configure>

=== jetty/jetty.project/jetty-ee9/jetty-ee9-tests/jetty-ee9-test-integration/src/test/resources/deploy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<Configure id="Server" class="org.eclipse.jetty.server.Server">
  <Call id="Environment" class="org.eclipse.jetty.util.component.Environment" name="ensure">
    <Arg>ee9</Arg>
  </Call>

  <Call name="addBean">
    <Arg>
      <New id="Deployer" class="org.eclipse.jetty.deploy.GoalDeployer">
        <Arg name="contexts"><Ref refid="contexts"/></Arg>

        <Call name="addBean">
          <Arg>
            <New id="deploymentScanner" class="org.eclipse.jetty.deploy.DeploymentScanner">
              <Arg name="server"><Ref refid="Server"/></Arg>
              <Arg name="deployer"><Ref refid="Deployer"/></Arg>

              <Call name="addMonitoredDirectory">
                <Arg>
                  <Call name="resolvedPath" class="org.eclipse.jetty.xml.XmlConfiguration">
                    <Arg>target</Arg>
                    <Arg>webapps</Arg>
                  </Call>
                </Arg>
              </Call>
              <Set name="scanInterval">1</Set>

              <Call name="configureEnvironment">
                <Arg>ee9</Arg>
                <Set name="defaultContextHandlerClass">org.eclipse.jetty.ee9.webapp.WebAppContext</Set>
                <Set name="extractWars">true</Set>
                <Set name="containerScanJarPattern">
                  <Property name="jetty.deploy.containerScanJarPattern">
                    <Default>.*/jetty-jakarta-servlet-api-[^/]*\.jar$|.*jakarta.servlet.jsp.jstl-.*\.jar$</Default>
                  </Property>
                </Set>
                <Set name="webInfScanJarPattern" property="jetty.deploy.webInfScanJarPattern" />
                <Set name="servletContainerInitializerExclusionPattern" property="jetty.deploy.servletContainerInitializerExclusionPattern" />
                <Set name="servletContainerInitializerOrder" property="jetty.deploy.servletContainerInitializerOrder" />
              </Call>
            </New>
          </Arg>
        </Call>
      </New>
    </Arg>
  </Call>
</Configure>

=== jetty/jetty.project/jetty-ee11/jetty-ee11-tests/jetty-ee11-test-weld-cdi-webapp/src/main/webapp/WEB-INF/jetty-env.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_10_0.dtd">

<Configure id="webAppCtx" class="org.eclipse.jetty.ee11.webapp.WebAppContext">
  <New id="BeanManager" class="org.eclipse.jetty.plus.jndi.Resource">
    <Arg>
      <Ref refid="webAppCtx"/>
    </Arg>
    <Arg>BeanManager</Arg>
    <Arg>
      <New class="javax.naming.Reference">
        <Arg>jakarta.enterprise.inject.spi.BeanManager</Arg>
        <Arg>org.jboss.weld.resources.ManagerObjectFactory</Arg>
        <Arg/>
      </New>
    </Arg>
  </New>
</Configure>

=== jetty/jetty.project/jetty-ee8/jetty-ee8-osgi/jetty-ee8-osgi-boot/jettyhome/etc/jetty-http.xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<!-- ============================================================= -->
<!-- Configure the Jetty Server instance with an ID "Server"       -->
<!-- by adding an HTTP connector.                                   -->
<!-- This configuration must be used in conjunction with jetty.xml -->
<!-- ============================================================= -->
<Configure id="Server" class="org.eclipse.jetty.server.Server">

  <!-- =========================================================== -->
  <!-- Add an HTTP Connector.                                       -->
  <!-- Configure an o.e.j.server.ServerConnector with a single     -->
  <!-- HttpConnectionFactory instance using the common httpConfig  -->
  <!-- instance defined in jetty.xml                               -->
  <!--                                                             -->
  <!-- Consult the javadoc of o.e.j.server.ServerConnector and     -->
  <!-- o.e.j.server.HttpConnectionFactory for all configuration    -->
  <!-- that may be set here.                                       -->
  <!-- =========================================================== -->
  <Call name="addConnector">
    <Arg>
      <New class="org.eclipse.jetty.server.ServerConnector">
        <Arg name="server"><Ref refid="Server" /></Arg>
        <Arg name="factories">
          <Array type="org.eclipse.jetty.server.ConnectionFactory">
            <Item>
              <New class="org.eclipse.jetty.server.HttpConnectionFactory">
                <Arg name="config"><Ref refid="httpConfig" /></Arg>
              </New>
            </Item>
          </Array>
        </Arg>
        <Set name="host"><Property name="jetty.http.host" /></Set>
        <Set name="port"><Property name="jetty.http.port" default="80" /></Set>
        <Set name="idleTimeout"><Property name="jetty.http.idleTimeout" default="30000"/></Set>
      </New>
    </Arg>
  </Call>

</Configure>

=== jetty/jetty.project/jetty-ee8/jetty-ee8-osgi/test-jetty-ee8-osgi/src/test/config/etc/jetty-http-boot-with-resources.xml
<?xml version="1.0"?><!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_10_0.dtd">

<!-- ============================================================= -->
<!-- Configure the Jetty Server instance with an ID "Server"       -->
<!-- by adding an HTTP connector.                                   -->
<!-- This configuration must be used in conjunction with jetty.xml -->
<!-- ============================================================= -->
<Configure id="Server" class="org.eclipse.jetty.server.Server">

  <!-- =========================================================== -->
  <!-- Add an HTTP Connector.                                       -->
  <!-- Configure an o.e.j.server.ServerConnector with a single     -->
  <!-- HttpConnectionFactory instance using the common httpConfig  -->
  <!-- instance defined in jetty.xml                               -->
  <!--                                                             -->
  <!-- Consult the javadoc of o.e.j.server.ServerConnector and     -->
  <!-- o.e.j.server.HttpConnectionFactory for all configuration    -->
  <!-- that may be set here.                                       -->
  <!-- =========================================================== -->
  <Call name="addConnector">
    <Arg>
      <New class="org.eclipse.jetty.server.ServerConnector">
        <Arg name="server"><Ref refid="Server" /></Arg>
        <Arg name="factories">
          <Array type="org.eclipse.jetty.server.ConnectionFactory">
            <Item>
              <New class="org.eclipse.jetty.server.HttpConnectionFactory">
                <Arg name="config"><Ref refid="httpConfig" /></Arg>
              </New>
            </Item>
          </Array>
        </Arg>
        <Call name="addEventListener">
          <Arg>
            <New class="org.eclipse.jetty.osgi.util.ServerConnectorListener">
              <Set name="sysPropertyName">boot.resources.port</Set>
            </New>
          </Arg>
        </Call>
        <Set name="host"><Property name="jetty.http.host" /></Set>
        <Set name="port"><Property name="jetty.http.port" default="80" /></Set>
        <Set name="idleTimeout"><Property name="jetty.http.idleTimeout" default="30000"/></Set>
      </New>
    </Arg>
  </Call>

</Configure>

=== jetty/jetty.project/jetty-demos/jetty-servlet5-demos/jetty-servlet5-demo-jndi-webapp/src/main/config/modules/demo.d/ee11-demo-jndi.xml
<?xml version="1.0"?><!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">

<!-- =============================================================== -->
<!-- Configure the test-jndi webapp                                  -->
<!-- =============================================================== -->
<Configure id="wac" class="org.eclipse.jetty.ee.webapp.WebAppContext">

  <New id="tx" class="org.eclipse.jetty.plus.jndi.Transaction">
    <Arg><Property name="environment" default="ee11"/></Arg>
    <Arg>
      <New class="org.example.MockUserTransaction" />
    </Arg>
  </New>

  <Set name="contextPath">/ee11-test-jndi</Set>
  <Set name="war"><Property name="jetty.webapps" default="." />/ee11-demo-jndi.war
  </Set>
  <Set name="extractWAR">true</Set>
  <Set name="copyWebDir">false</Set>
  <Set name="configurationDiscovered">true</Set>

  <!-- Define an env entry with ee11 environment scope for java:comp/env                   -->
  <New id="woggle" class="org.eclipse.jetty.plus.jndi.EnvEntry">
    <Arg>
      <Property name="environment" default="ee11"/>
    </Arg>
    <Arg>woggle</Arg>
    <Arg type="java.lang.Integer">4000</Arg>
    <Arg type="boolean">false</Arg>
  </New>

  <!-- Define an env entry with webapp scope for java:comp/env                   -->
  <New id="wiggle" class="org.eclipse.jetty.plus.jndi.EnvEntry">
    <Arg>
      <Ref refid="wac" />
    </Arg>
    <Arg>wiggle</Arg>
    <Arg type="java.lang.Double">100</Arg>
    <Arg type="boolean">true</Arg>
  </New>

  <!-- Mail Session setup                                          -->
  <New id="xxxmail" class="org.eclipse.jetty.plus.jndi.Resource">
    <Arg>
      <Ref refid="wac" />
    </Arg>
    <Arg>mail/Session</Arg>
    <Arg>
      <New class="org.eclipse.jetty.ee.jndi.factories.MailSessionReference">
        <Set name="user">CHANGE-ME</Set>
        <Set name="password">CHANGE-ME</Set>
        <Set name="properties">
          <New class="java.util.Properties">
            <Put name="mail.smtp.auth">false</Put> <!-- change to true if you want to authenticate -->
            <Put name="mail.smtp.host">CHANGE-ME</Put>
            <Put name="mail.from">CHANGE-ME</Put>
            <Put name="mail.debug">false</Put>
          </New>
        </Set>
      </New>
    </Arg>
  </New>

  <!-- A mock DataSource                                           -->
  <New id="mydatasource" class="org.eclipse.jetty.plus.jndi.Resource">
    <Arg>
      <Ref refid="wac" />
    </Arg>
    <Arg>jdbc/mydatasource</Arg>
    <Arg>
      <New class="org.example.MockDataSource" />
    </Arg>
  </New>

</Configure>
